name: notation-azure-kv-sign
description: notation sign with notation akv plugin
inputs:
  key_id:
    description: Key identifier for the signing key pair from AKV
    required: true
  target_artifact_reference:
     description: 'Reference of the target artifact to be signed. <registry>/<repo>@<digest>'
     required: true
  plugin_config:
     description: '{key}={value} pairs that are passed as it is to akv plugin'
     required: false
  plugin_oci_ref:
     description: 'Reference of notation akv plugin as OCI artifact'
     required: false
runs:
  using: node16
  main: dist/index.js